fix: frontend docker build.

diff --git a/Dockerfile.backend b/Dockerfile.backend
--- a/Dockerfile.backend
+++ b/Dockerfile.backend
@@ -1,18 +1,25 @@
 # Dockerfile.backend - for backend project
 
-# --- -base- ---
-FROM node:lts-alpine as base
+# --- -deps- ---
+# Install dependencies only when needed
+FROM node:lts-alpine as deps
+# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
 RUN apk add --no-cache libc6-compat
 ENV YARN_CACHE_FOLDER=./yarn_cache
 # Create and change to the app directory.
 WORKDIR /root/app
 
-# Copy application dependency manifests to the container image.
-COPY package.json ./yarn.* ./
-RUN yarn install --frozen-lockfile --omit=dev --ignore-scripts
+# Install dependencies based on the preferred package manager
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile --omit=dev --ignore-scripts; \
+  elif [ -f package-lock.json ]; then npm ci --omit=dev --ignore-scripts; \
+  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --omit=dev --ignore-scripts; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
 # --- -build- ---
-FROM base as build
+FROM deps as build
 # Copy local code to the container image.
 COPY . ./
 ENV NODE_ENV=production
@@ -24,15 +31,14 @@ RUN ls -lah dist/apps/backend
 # --- -deploy- ---
 FROM build as deploy
 WORKDIR /root/app/dist/apps/backend
-# COPY --from=build /root/app/dist/apps/backend .
-COPY --from=base /root/app/node_modules ./node_modules
 
-RUN yarn install --production --omit=dev --ignore-scripts
+COPY --from=deps /root/app/node_modules ./node_modules
+
 # dependencies that fastify needs
+RUN yarn install --production --omit=dev --ignore-scripts
 RUN yarn add reflect-metadata tslib rxjs
 
 # --- --- ---
-# CMD ls -las /root/app && tail -f /dev/null
 RUN ls -lah /root/app/dist/apps/backend
 
 # Run the web service on container startup.
